[INFO]: Run Directory: /openlane/designs/project_4/runs/RUN_2025.06.01_19.55.26
[INFO]: Saving runtime environment...
[INFO]: Preparing LEF files for the nom corner...
[INFO]: Preparing LEF files for the min corner...
[INFO]: Preparing LEF files for the max corner...
[INFO]: Running linter (Verilator) (log: designs/project_4/runs/RUN_2025.06.01_19.55.26/logs/synthesis/linter.log)...
[INFO]: 0 errors found by linter
[INFO]: 0 warnings found by linter
[INFO]: Running Synthesis (log: designs/project_4/runs/RUN_2025.06.01_19.55.26/logs/synthesis/1-synthesis.log)...
[INFO]: Running Single-Corner Static Timing Analysis (log: designs/project_4/runs/RUN_2025.06.01_19.55.26/logs/synthesis/2-sta.log)...
[ERROR]: during executing sta script /openlane/scripts/openroad/sta/multi_corner.tcl
[ERROR]: Log: designs/project_4/runs/RUN_2025.06.01_19.55.26/logs/synthesis/2-sta.log
[ERROR]: Last 10 lines:
Using 1e+03 for resistance...
Using 1e-09 for time...
Using 1e+00 for voltage...
Using 1e-03 for current...
Using 1e-09 for power...
Using 1e-06 for distance...
Reading netlist '/openlane/designs/project_4/runs/RUN_2025.06.01_19.55.26/results/synthesis/top.v'…
Reading design constraints file at '/openlane/designs/project_4/system.sdc'…
Error: multi_corner.tcl line 43, cannot open '/openlane/designs/project_4/system.sdc'.
child process exited abnormally

[ERROR]: Creating issue reproducible...
[INFO]: Saving runtime environment...
[INFO]: Reproducible packaged: Please tarball and upload 'designs/project_4/runs/RUN_2025.06.01_19.55.26/issue_reproducible' if you're going to submit an issue.
[ERROR]: Step 2 (synthesis) failed with error:
-code 1 -level 0 -errorstack {INNER {invokeStk1 throw_error} CALL {run_tcl_script -tool sta -no_consume /openlane/scripts/openroad/sta/multi_corner.tcl -indexed_log /openlane/designs/project_4/runs/RUN_2025.06.01_19.55.26/logs/synthesis/2-sta.log -save to=/openlane/designs/project_4/runs/RUN_2025.06.01_19.55.26/results/synthesis,noindex,sdf,lib -netlist_in} CALL {run_sta_script /openlane/scripts/openroad/sta/multi_corner.tcl -indexed_log /openlane/designs/project_4/runs/RUN_2025.06.01_19.55.26/logs/synthesis/2-sta.log -save to=/openlane/designs/project_4/runs/RUN_2025.06.01_19.55.26/results/synthesis,noindex,sdf,lib -netlist_in} CALL {run_sta -log /openlane/designs/project_4/runs/RUN_2025.06.01_19.55.26/logs/synthesis/sta.log -netlist_in -pre_cts -save_to /openlane/designs/project_4/runs/RUN_2025.06.01_19.55.26/results/synthesis -tool sta} CALL run_synthesis CALL {run_non_interactive_mode -design project_4}} -errorcode NONE -errorinfo {
    while executing
"throw_error"
    (procedure "run_tcl_script" line 219)
    invoked from within
"run_tcl_script -tool sta -no_consume {*}$args"
    (procedure "run_sta_script" line 2)
    invoked from within
"run_$arg_values(-tool)_script $::env(SCRIPTS_DIR)/openroad/sta/multi_corner.tcl {*}$arg_list"
    (procedure "run_sta" line 109)
    invoked from within
"run_sta -log $::env(synthesis_logs)/sta.log  -netlist_in  -pre_cts  -save_to $::env(synthesis_results)  -tool sta"
    (procedure "run_synthesis" line 50)
    invoked from within
"run_synthesis"} -errorline 1
[INFO]: Saving current set of views in 'designs/project_4/runs/RUN_2025.06.01_19.55.26/results/final'...
[INFO]: Generating final set of reports...
[ERROR]: Failed to create manufacturability and metric reports:
[ERROR]: Traceback (most recent call last):
  File "/openlane/scripts/generate_reports.py", line 184, in <module>
    cli()
  File "/nix/store/8ywrzlq8yyqrif2sfvbgg8vsxhj80ry7-python3-3.11.9-env/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/8ywrzlq8yyqrif2sfvbgg8vsxhj80ry7-python3-3.11.9-env/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/nix/store/8ywrzlq8yyqrif2sfvbgg8vsxhj80ry7-python3-3.11.9-env/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/8ywrzlq8yyqrif2sfvbgg8vsxhj80ry7-python3-3.11.9-env/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openlane/scripts/generate_reports.py", line 51, in cli
    report = Report(design, tag, design_name, params, run_path).get_report()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openlane/scripts/report/report.py", line 809, in get_report
    *self.extract_all_values(),
     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openlane/scripts/report/report.py", line 359, in extract_all_values
    power_report = Artifact(
                   ^^^^^^^^^
  File "/openlane/scripts/report/report.py", line 62, in __init__
    self.pathname = matches[0]
                    ~~~~~~~^^^
IndexError: list index out of range
[INFO]: Saving runtime environment...
[ERROR]: Flow failed.
